[package]
name = "fta-transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
# Shared
fta-types = { path = "../fta-types" }
fta-errors = { path = "../fta-errors" }
fta-database = { path = "../fta-database" }
fta-validation = { path = "../fta-validation" }

# Workspace dependencies
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
paginator-rs.workspace = true
paginator-utils.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
utoipa.workspace = true
uuid.workspace = true

[lints]
workspace = true
