[package]
name = "fta-budgets"
version = "0.1.0"
edition = "2021"

[dependencies]
fta-types = { path = "../fta-types" }
fta-errors = { path = "../fta-errors" }
fta-database = { path = "../fta-database" }
fta-validation = { path = "../fta-validation" }
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
paginator-rs.workspace = true
paginator-utils.workspace = true
paginator-axum.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true

[lints]
workspace = true
