[profile.default]
failure-output = "immediate"
success-output = "final"
status-level = "pass"
test-threads = 8

[profile.default.junit]
path = "target/nextest/default/junit.xml"

[profile.ci]
failure-output = "immediate-final"
success-output = "final"
retries = { backoff = "exponential", count = 2, delay = "1s" }

[profile.fast]
test-threads = 16
failure-output = "immediate"
success-output = "never"

[[profile.default.overrides]]
filter = 'test(timestamp)'
slow-timeout = { period = "60s", terminate-after = 2 }
